services:
  voice-bot:
    image: voice-shut-up-bot:latest
    build: .
    container_name: voice-shut-up-bot
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "5"
